### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by SravaniDhavala** [MustafaFerhan/MFCalendarView#2]
Hello, here in the calendar
1. I want to pass few dates statically which highlight the background of the cell. But i could pass only one date.
2. when we change the month, the date which has been set statically is erasing(cell is deselected) when i come back to the previous month.

Can you provide me a solution?
Thanks in advance.

**Comment by nitinjadhav** [comment]
how to set min and max date ?

**Comment by vinod1988** [comment]
### Pass your static date something like that.

  Just follow the below steps  
- ArrayList<String> eventDays = new ArrayList<String>();
- eventDays.add("2015-10-22");
- mf.setEvents(eventDays);

It will work. no issue while navigating next or previous  month.
